// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Newtonsoft.Json.Combinators")>]
[<assembly: AssemblyProductAttribute("Newtonsoft.Json.Combinators")>]
[<assembly: AssemblyDescriptionAttribute("Parser combinators for Newtonsoft.Json")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Newtonsoft.Json.Combinators"
    let [<Literal>] AssemblyProduct = "Newtonsoft.Json.Combinators"
    let [<Literal>] AssemblyDescription = "Parser combinators for Newtonsoft.Json"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
